services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - '5644:5432'
    environment:
      POSTGRES_DB: icc-cms
      POSTGRES_USER: icc
      POSTGRES_PASSWORD: icc123
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    networks:
      - icc_network

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
       - '19111:9000'   
       - '19012:9001'  
    command: server /data --console-address ":9001"
    # volumes:
    #   - minio_data:/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - icc_network

  createbuckets:
    image: minio/mc
    container_name: createbucket
    entrypoint: >
      /bin/sh -c "
      echo '⏳ Waiting for MinIO API...';
      until mc alias set local http://minio:9000 minioadmin minioadmin; do sleep 2; done;
      until mc mb local/icc-dev; do sleep 2; done;
      mc anonymous set public local/icc-dev;
      echo '✅ Bucket created';
      exit 0;"
    depends_on:
      minio:
        condition: service_healthy
    restart: 'no'
    networks:
      - icc_network

volumes:
  pgdata:
  minio_data:

networks:
  icc_network:
    driver: bridge